# Generated by Django 5.0.1 on 2024-01-12 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='название')),
                ('model', models.CharField(max_length=150, verbose_name='модель')),
                ('release_date', models.DateTimeField(verbose_name='время выхода на рынок')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.factory', verbose_name='производитель')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
