# Generated by Django 4.2.4 on 2024-01-20 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('model', models.CharField(max_length=150, verbose_name='модель')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('quantity', models.IntegerField(verbose_name='количество')),
                ('release_date', models.DateTimeField(verbose_name='время выхода на рынок')),
                ('hierarchy', models.IntegerField(default=0, verbose_name='иерархия')),
                ('owner', models.ForeignKey(limit_choices_to={'link': 'завод'}, on_delete=django.db.models.deletion.CASCADE, to='links.link', verbose_name='владелец')),
                ('supplier', models.ForeignKey(limit_choices_to={'link': 'завод'}, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_products', to='links.link', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
