# Generated by Django 4.2.4 on 2024-01-15 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_link_link'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(limit_choices_to={'link': 'завод'}, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_products', to='links.link', verbose_name='производитель'),
        ),
    ]
