# Generated by Django 4.2.4 on 2024-01-20 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='owner',
            new_name='owner_link',
        ),
    ]
