# Generated by Django 4.2.4 on 2024-01-21 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
        ('product', '0003_product_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner_link',
            field=models.ForeignKey(limit_choices_to={'link': 'завод'}, on_delete=django.db.models.deletion.CASCADE, to='links.link', verbose_name='владелец продукта'),
        ),
    ]
