# Generated by Django 4.2.4 on 2024-01-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='количество товара')),
                ('data', models.DateTimeField(verbose_name='дата создания')),
                ('hierarchy', models.IntegerField(default=0, verbose_name='иерархия')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_as_buyer', to='links.link', verbose_name='покупатель товара')),
                ('product_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_with_cost', to='product.product', verbose_name='стоимость товара')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_with_name', to='product.product', verbose_name='наименование товара')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_as_supplier', to='links.link', verbose_name='поставщик товара')),
            ],
            options={
                'verbose_name': 'закупка',
                'verbose_name_plural': 'закупки',
            },
        ),
    ]
