# Generated by Django 4.2.4 on 2024-01-16 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product_cost',
        ),
    ]
