# Generated by Django 4.2.4 on 2024-01-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_purchase_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='owner',
        ),
    ]
