# Generated by Django 4.2.4 on 2024-01-17 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0006_alter_link_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='долг')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_debt_set', to='links.link', verbose_name='заемщик')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owed_debt_set', to='links.link', verbose_name='должник')),
            ],
            options={
                'verbose_name': 'долг',
                'verbose_name_plural': 'долги',
            },
        ),
    ]
