# Generated by Django 4.2.4 on 2024-01-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(choices=[('завод', 'завод'), ('индивидуальный предприниматель', 'индивидуальный предприниматель'), ('розничная сеть', 'розничная сеть')], max_length=50, verbose_name='звено сети'),
        ),
    ]
